apiVersion: webapp.my.domain/v1
kind: Guestbook
metadata:
  name: guestbook-sample
spec:
  foo: test
  resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cfgmap
      data:
        env: dev
